name: my first script

on:
  push:
    branches:
      - master
jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - name: show files
        run: ls -la

      - name: checkout
        uses: action/checkout@6.0.2

      - name: check checkout
        run: ls -la
