on: 
  workflow_dispatch:
    inputs:
      x:
        description: "chose one"
        required: true
        type: choice
        options:
          - develop
          - prodaction
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: know cpu type
        run: lscpu

      - name: show ram details
        run: free -h

       
      - name: show desk details
        run: df -h

      - name: install htop
        run: sudo apt install -y htop

      - name : show the varibalis
        run: echo "hi $(( inputs.x ))
    
        
          
