name: speednet
on:
  push:
    branches: 
      - master

jobs:
  try-test-net:
    runs-on: ubuntu-latest

    steps:
      - name: download speedtest-cli
        run: sudo apt install speedtest-cli

      - name: run speedtest-cli
        run: speedtest

      - name: ping
        run: timeout 10 ping 8.8.8.8
  
